# GitHub Action for merging into the development branch
# and for pull requests against the development branch.
# See /docs/cicd.md for more information
name: Lower-stage Deployment or PR

on:
  push: # for push or merge into branch
    branches:  # FIXME: change if have different branch names
      - dev
      - qa
      - staging
  pull_request: # for PR against the following branch(es)
    branches:  # FIXME: change if have different branch name
      - dev

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1  # FIXME: set desired region
  STAGE_NAME: ${{ github.ref_name }}  # branch name

jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Code Tests
        run: npm run analyze
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        run: npm run deploy
      - name: Integration Tests
        if: ${{ github.event_name == 'push' }}
        run: npm run test:client-api -w cloud-test
